# Generated by Django 4.2 on 2024-06-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_driver_latitude_alter_driver_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gear_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_power',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_speed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='start',
            field=models.ManyToManyField(blank=True, related_name='start', to='vehicle.stop'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='zero_to_sixty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='latitude',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='longitude',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ManyToManyField(blank=True, related_name='vehicle', to='vehicle.vehicle'),
        ),
    ]
