# Generated by Django 4.2 on 2024-08-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_driver_id_driver_date_of_birth_driver_driver_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
