# Generated by Django 4.2 on 2024-02-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="static/images/profile.svg",
                null=True,
                upload_to="media/profile",
            ),
        ),
    ]
