# Generated by Django 4.2 on 2024-02-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="student_number",
        ),
    ]
