<<<<<<< HEAD
# Generated by Django 4.2 on 2024-04-01 21:41
=======
# Generated by Django 4.2 on 2024-03-08 19:31
>>>>>>> 98af928bb2d038c90054482f1e354ee363899ce6

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0002_alter_driver_latitude_alter_driver_longitude'),
=======
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 98af928bb2d038c90054482f1e354ee363899ce6
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1)),
<<<<<<< HEAD
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='vehicle.driver')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
=======
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='vehicle.driver')),
                ('users', models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL)),
>>>>>>> 98af928bb2d038c90054482f1e354ee363899ce6
            ],
        ),
    ]
